# Generated by Django 5.2.15 on 2026-06-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FISHING_GEAR', 'Fishing Gear'), ('DIVING_GEAR', 'Diving Gear'), ('MARINE_EQUIPMENT', 'Marine Equipment'), ('OCEAN_APPAREL', 'Ocean Apparel'), ('OCEAN_ACCESSORIES', 'Ocean Accessories'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
