# Generated by Django 5.2.15 on 2026-06-22 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('VOUCHER', 'Voucher'), ('PROMO', 'Promo')], max_length=20)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value_type', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('discount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='discounts.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_usage', models.IntegerField()),
                ('used_count', models.IntegerField(default=0)),
                ('discount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='discounts.discount')),
            ],
        ),
    ]
