# Generated by Django 5.2.15 on 2026-06-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryjob',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('TAKEN', 'Taken'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
    ]
