# Generated by Django 5.2.15 on 2026-06-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
