# Generated by Django 5.2.15 on 2026-06-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, choices=[('JAKARTA', 'Jakarta'), ('TANGERANG', 'Tangerang'), ('ANYER', 'Anyer'), ('BALI', 'Bali'), ('LOMBOK', 'Lombok'), ('BATAM', 'Batam'), ('MANADO', 'Manado'), ('MAKASSAR', 'Makassar'), ('SURABAYA', 'Surabaya'), ('RAJA_AMPAT', 'Raja Ampat')], max_length=50, null=True),
        ),
    ]
